### ISSUE TITLE
Upgrade of OctoPrint 1.4.0 to 1.4.2 inside addon fails

### ISSUE THREAD

**Issue by fredrikbaberg** [fredrikbaberg/hassio-addons#104]
The upgrade fails at `psutil` due to `gcc` missing, at least on Pi3.

**Comment by fredrikbaberg** [comment]
A workaround could be to set `add_build_packages: true` and restart the addon __before__ the upgrade.

**Comment by cachrisman** [comment]
I can report that adding the build packages, restarting, then upgrading worked successfully for me!

**Comment by fredrikbaberg** [comment]
Closing this.
