### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by fredrikbaberg** [fredrikbaberg/hassio-addons#106]
Next update should move to Python3.
OctoPi has a [upgrade script](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/), should look at something similar (or "just" backup, replace and restore?)

**Comment by woody4165** [comment]
Hi and thanks for sharing this addon for HA

I'm having some issues on installing some plugin for Octoprint like OctoPrint-Telegram and Bed Level Visualizer

As far as I understood the log, the issue is the Python version.

Is there a way to upgrade manually or will I break the addon?

Thanks

**Comment by fredrikbaberg** [comment]
This issue is for migrating to Python3, I haven't done that yet as I haven't figured out a safe way to do so without breaking current installs (and a lack of time).

It would help to see the relevant part of the log. Is the issue that the version of Python2 is too old, that Python3 is required, or a missing dependency? Have you tried the "add_build_packages" option of the addon?

**Comment by woody4165** [comment]
> Have you tried the "add_build_packages" option of the addon? I tried to install the Telegram plugin, it fails due to missing dependencies if it is not enabled. Bed level visualizer also seem to install with that option enabled.

Thanks!

That did the trick.

I haven't thought about it and now both the plugin I was trying to install, are installed properly.
If you want I can delete my messages in this post, so it can be clean...

Thanks again...

**Comment by fredrikbaberg** [comment]
> I haven't thought about it and now both the plugin I was trying to install, are installed properly.
> If you want I can delete my messages in this post, so it can be clean...
> 

Good that it works! No need to delete, it may be of help to someone else in the future - and a reminder to myself that I should make sure to address this in the documentation.

**Comment by fredrikbaberg** [comment]
"OctoPrint Next" is based on Python3. I'll avoid the upgrade path due to the risk of breaking the install.
