### ISSUE TITLE
Connect Prusa Slicer

### ISSUE THREAD

**Issue by MatGriffin** [fredrikbaberg/hassio-addons#112]
I'm trying to connect Prusa Slicer to Octoprint HA add-on. To do this I need to add the IP of the Rpi that Octoprint is on but when I add my Home assistant IP it can't find it so it looks like Prusa slicer can't connect to this add-on (?)

**Comment by fredrikbaberg** [comment]
Which Hostname/IP and port did you use?

I believe this should work, but it requires to set a port for WebUI (5000 is default but normally disabled).
Could you try to:
- In addon settings, specify a port for WebUI, e.g. 5000. This should allow you to access OctoPrint WebUI on "http://homeassistant.local:5000" (depending on hostname and port used).
- In PrusaSlicer, under "Hostname, IP or URL", use the port specified, e.g. "http://homeassistant.local:5000".

**Comment by MatGriffin** [comment]
Found it. Working :)
Thank you
