### ISSUE TITLE
Add Marlin Binary Protocol Package

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/hassio-addons#183]
As needed for this plugin: https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/blob/devel/doc/marlinbft.md the python bin `marlin-binary-protocol` is needed.
When installing it manually with:
`pip3 install https://github.com/p3p/pyheatshrink/releases/download/0.3.3/pyheatshrink-pip.zip`
and followed by:
`pip3 install marlin-binary-protocol`
It is missing gcc, which can be installed with:
```apk add python3-dev gcc libc-dev```
Not sure what is needed for debian
probably: `apt-get install python3-dev`

**Comment by fredrikbaberg** [comment]
Thank you for all the reports!

It would be best to solve that from the plugin side, so I've created an issue there, and will make sure to add the requirements on `gcc` etc. to the addon.

**Comment by bruvv** [comment]
as mentoined there, gcc is needed for heatshrink, which has to be build in the octoprint env.

**Comment by fredrikbaberg** [comment]
Adding `gcc` is not an issue. There was previously a configuration option to install development packages (including gcc), but I'll probably just add it from the start instead. Disadvantage is that the plugin will be larger from the start.

**Comment by bruvv** [comment]
Awesome job! I managed to install `pyheatshrink` in de container itself. So it should be an option. What is the error you're getting ?

**Comment by bruvv** [comment]
As I'm not home I cannot check ATM what I did. From what I can see everything should be good. Will look into it later this week.

**Comment by bruvv** [comment]
It was pretty easy in the end :) https://github.com/fredrikbaberg/hassio-addons/pull/204

**Comment by fredrikbaberg** [comment]
Thank you. I've merged the PR now, will need to build new images before it's available.

**Comment by fredrikbaberg** [comment]
This should now be included in addon "3DPrinter", which is intended to replace all current "OctoPrint" variations in this repository.
