### ISSUE TITLE
[OctoPrint Next Dev] Discovery plugin uses wrong IP address

### ISSUE THREAD

**Issue by fredrikbaberg** [fredrikbaberg/hassio-addons#198]
OctoPrint uses internal IP address, which causes some issues with autodiscovery.

Not sure if this can be fixed, as it can be set in config.yaml but that would cause issues if the hostname/IP changes.

**Comment by maroliar** [comment]
I had that problem too.. I've be restarted my ender, and disconnected the usb cable, and now the ip changed 172.30.33.1 to 172.30.33.2. Is there any way to set a manual ip?

**Comment by fredrikbaberg** [comment]
Not that I know of. If it´s for the OctoPrint integration you can try to use the hostname of the addon, `774437fd-3dprinter`.

**Comment by Carapijo** [comment]
Im trying to use Printoid, but can´t reach the interface via IP, how could i use that hostname in that?

**Comment by fredrikbaberg** [comment]
> Im trying to use Printoid, but can´t reach the interface via IP, how could i use that hostname in that?

That hostname (774437fd-3dprinter) is only available inside Home Assistant OS, and sometimes between other addons. It will not work for an external device, which I assume you are running Printoid on.
You either need to:
- Set an external port in addon settings to make it available on the network (assuming you trust the network, NEVER expose OctoPrint directly to internet or a network you don't trust - see e.g. https://octoprint.org/blog/2018/09/03/safe-remote-access/ and https://community.octoprint.org/t/access-your-octoprint-remotely/3628).
- Setup a reverse proxy in Home Assistant (Traefik and nginx are two examples).
