### ISSUE TITLE
Webrtc now supported in home assistant

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/hassio-addons#236]
Just found this repo in the comments on the new home assistant release page (version 11)
https://github.com/OctoPrint/OctoPrint/pull/4225
Perhaps some useful information?

**Comment by fredrikbaberg** [comment]
So I remember how this is connected:
- WebRTC support has been added to Home Assistant 2021.11 (https://www.home-assistant.io/blog/2021/11/03/release-202111/).
- WebRTC support to be added to OctoPrint 1.8.0

As a first step I'll have to see if it's straightforward to compile [mpromonet/webrtc-streamer](https://github.com/mpromonet/webrtc-streamer) for Alpine.

**Comment by fredrikbaberg** [comment]
Would like to see this added, but it would be a different add-on and I don't currently have time to look at it. Feel free to make PR to new repo: https://github.com/fredrikbaberg/ha-3dprinter-addons
