### ISSUE TITLE
OctoPrint + DietPi + Supervised install = missing netifaces library

### ISSUE THREAD

**Issue by alryaz** [fredrikbaberg/hassio-addons#237]
Hola!

First and foremost, thank you for developing this beautiful add-on!

Unfortunately, I encountered a major issue with one of the newer versions of it. I tried migrating from the original _octoprint_ add-on to the _3dprinter_ one, and encountered an error while starting it up:

```
Traceback (most recent call last):
  File "/data/python/octoprint/bin/octoprint", line 8, in <module>
    sys.exit(main())
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/__init__.py", line 959, in main
    from octoprint.util.fixes import patch_sarge_async_on_py2
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 52, in <module>
    from octoprint.util.connectivity import ConnectivityChecker  # noqa: F401
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/util/connectivity.py", line 12, in <module>
    from octoprint.util.net import resolve_host, server_reachable
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/util/net.py", line 14, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'
```

I tried browsing through `/usr/share/hassio/addons/data/774437fd_3dprinter/python/octoprint/lib/python3.9/site-packages/` only to discover literal netifaces package was actually missing. I am not completely sure why that's the case; given that there is an implementation-specific shared library available, no issues should arise. Naturally, I tried symlinking `netifaces.so` to it (`ln -s netifaces{.cpython-39-arm-linux-gnueabihf,}.so`). Here is the result:

```
Traceback (most recent call last):
  File "/data/python/octoprint/bin/octoprint", line 8, in <module>
/* <same lines> */
    import netifaces
ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /data/python/octoprint/lib/python3.9/site-packages/netifaces.so)
```

I might attempt to copy over the `/lib/ld-linux-armhf.so.3` binary into the container, however I fear I might end up in an endless cycle of copying the files over and over.

I understand that this might not be a supported use case, neither can I confirm this occuring on other such installations.

**Comment by fredrikbaberg** [comment]
Hi, and thank you!

I should clarify that I haven't tried to migrate data between the addon versions, I've moved some files around to have everything more structured. How did you do the migration, backup and restore feature of OctoPrint?

I don't think I've seen this issue before, but I'm only testing the addon on aarch64 (with printer connected) and amd64 (just installing and configuring). I suspect you are somewhat comfortable with terminal commands as you wrote about symlinking and are using a non-default setup? You could try a variation of what is suggested in the following posts:
- https://community.octoprint.org/t/solved-octoprint-not-running-after-update-to-1-4-2/22793/9
- https://community.octoprint.org/t/no-module-named-netifaces-error/26103

Not sure if power off and on will help, it was one of the suggestions, but you could try to reinstall _netifaces_. For my install, accessing through the SSH and Web Terminal addon:
> docker exec -it addon_774437fd_3dprinter /bin/bash
> source /data/python/octoprint/bin/activate
> pip install --force-reinstall netifaces

I think that should solve the issue with netifaces, but there is a risk other issues appears after that. A reinstall of OctoPrint may be necessary, should be something like `pip install --force-reinstall OctoPrint==1.7.2`.

On a side note, there is a high probability your OctoPrint `config.yaml` will attempt to access folders that do not exist. You can compare your file with the updated one here: https://github.com/fredrikbaberg/hassio-addons/blob/master/3dprinter/rootfs/root/config/octoprint/config.yaml

**Comment by alryaz** [comment]
Unfortunately, the issue with `docker exec -it addon... /bin/bash` is that the container must be running, and any update will cause a reset. S6 shuts the container down before I can successfully execute the target command.

I will attempt to migrate to ARM v8 (64-bit) DietPi image (yup, apparently I forgot to mention I'm using ARM v7 @ 32-bit) and post the results.

**Comment by fredrikbaberg** [comment]
I'll have a look two things while I wait for your results:
- See if I can prevent the addon from terminating.
- See if I can add a recovery option (again), that does `pip install --force-reinstall OctoPrint` (and netifaces if needed).

**Comment by fredrikbaberg** [comment]
I've now artificially broken an install through removing `netifaces`, and think I know where the startup fails. If you disable OctoPrint in addon settings it should be possible to access the addon.

I haven't figured out why `netifaces` is missing, but am testing an update that has a check and attempt to repair. It should be ready before monday.

**Comment by fredrikbaberg** [comment]
I've published 2021.11.2 that contains an attempt at automatically repairing this.

**Comment by alryaz** [comment]
I know there is a package called `py-netifaces` in the alpine repo. I tried adding it my inheriting Dockerfile, but unfortunately my docker environment is plagued with a bug where it can't reach mirrors during build.

**Comment by fredrikbaberg** [comment]
I'll try adding that to the image, just started the build which will take roughly one hour to complete. If everything seems good I'll merge the changes this evening.

Any success with the migration to 64-bit?

**Comment by fredrikbaberg** [comment]
Building worked, update should now be available.

**Comment by fredrikbaberg** [comment]
I installed Home Assistant OS 32-bit on a Pi 3B and got the issue, so now I should be able to debug it myself.

**Comment by alryaz** [comment]
I managed to finalize my transition to the 64-bit DietPi images (armv8, I must note), however due to an issue described in #245 I wasn't able to finalize my installation.

**Comment by fredrikbaberg** [comment]
Just wanted to note that it doesn't seem like `netifaces` is the only package affected by this. If the workaround in 2021.11.5 doesn't work I may have to disable support for `armv7`.

**Comment by fredrikbaberg** [comment]
I'll close this issue as I believe it is resolved. Please let me know if it happens again.
