### ISSUE TITLE
GHCR.io requires authentication (PR #242)

### ISSUE THREAD

**Issue by alryaz** [fredrikbaberg/hassio-addons#245]
Hola! I attempted to install 3D Printer add-on today, and stumbled upon the following issue (possibly introduced in PR #242):

`21-11-14 09:04:59 ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/fredrikbaberg/addon-3dprinter-aarch64:2021.11.4: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2021.11.4&fromImage=ghcr.io%2Ffredrikbaberg%2Faddon-3dprinter-aarch64: Internal Server Error ("Head "https://ghcr.io/v2/fredrikbaberg/addon-3dprinter-aarch64/manifests/2021.11.4": denied")`

Sending GET request to `https://ghcr.io/v2/fredrikbaberg/addon-3dprinter-aarch64/manifests/2021.11.4` yields an "UNAUTHORIZED" error (albeit this observation might not be relevant to solving the issue at all).

I suppose the image has not been made public?

**Comment by fredrikbaberg** [comment]
Sorry about that, it should be fixed now. I tried to migrate the images for 3dprinter addon from Docker Hub to ghcr but they where never uploaded. I did it manually for now, will have to figure out why the build script fails later.

**Comment by fredrikbaberg** [comment]
GitHub Action for building should now be fixed, so it will hopefully not happen again.
