### ISSUE TITLE
[3D printer] Unable to install pandas

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/hassio-addons#246]
I tried everything to get pandas to install in the 3D printer addon but I keep getting the following error:
![afbeelding](https://user-images.githubusercontent.com/3063928/141677244-4c52a919-3c77-4e47-9377-c03287edce8b.png)
```Original error was: Error loading shared library /tmp/pip-build-env-3zqirbzf/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-musl.so: Operation not permitted```
As can be seen in the beginning, numpy is installed.
The dir `/tmp/pip-build-env-3zqirbzf/overlay/lib/python3.9/site-packages/numpy/core/` does not exist after seening that error.

**Comment by fredrikbaberg** [comment]
It looks like you are running the command by hand? Could you try to do `source /data/python/octoprint/bin/activate` first, to ensure it is using the correct venv?

If that doesn't work I'll have to look into this after I've fixed #237, as I suspect that blocks all 32-bit systems right now.

**Comment by bruvv** [comment]
Correct, since pandas is needed by the plugin stats and stats is not able to install pandas I tried installing it by hand. I tried using the correct venv but same error.

**Comment by fredrikbaberg** [comment]
Closing this as I haven't been able to work on it and haven't seen any replies.

Suspect it works with new repo: https://github.com/fredrikbaberg/ha-3dprinter-addons
