### ISSUE TITLE
Unable to update/reinstall 3D Printer anymore

### ISSUE THREAD

**Issue by maroliar** [fredrikbaberg/hassio-addons#248]
When i try to update to last version:

Can't install ghcr.io/fredrikbaberg/addon-3dprinter-aarch64:2021.11.4: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=2021.11.4&fromImage=ghcr.io%2Ffredrikbaberg%2Faddon-3dprinter-aarch64: Internal Server Error ("manifest unknown")

I uninstalled and tried to install again, but got same error.

**Comment by fredrikbaberg** [comment]
Thank you for letting me know, it should be fixed now.

I did some changes to how the image is built, which took longer than expected.
