### ISSUE TITLE
Klipper and ADXL345 board

### ISSUE THREAD

**Issue by bruvv** [fredrikbaberg/hassio-addons#261]
Do you know if there is a way to use the ADXL345 with klipper without a raspberry pi?

**Comment by fredrikbaberg** [comment]
Not other than what is written on the Klipper site (https://www.klipper3d.org/Measuring_Resonances.html).
ADXL345 currently doesn't work on Raspberry Pi with the addon, possibly due to permission errors. I haven't figured out that part yet, so for now I have a second SD card with FluiddPi.

**Comment by fredrikbaberg** [comment]
Closing this as I still don't know.
