### ISSUE TITLE
Included mjpeg streamer not working

### ISSUE THREAD

**Issue by piechade** [fredrikbaberg/hassio-addons#279]
Hello,

I'm trying to get my webcam working.

Using your separated mjpg-streamer with the parameter `mjpg_input: input_uvc.so -n -r 1280x720 -f 60` works perfectly.

But if I want to use it with 3DPrinter 2021.11.7 ant following option, nothing works.
```
mjpg_input: '-i "input_uvc.so -n -r 1280x720 -f 60"'
mjpg_output: '-o "output_http.so -w /www_mjpg -p 8080"'
octoprint: true
mjpg_streamer: true
recovery: false
```

What I need to set in octoprint as URL?

**Comment by piechade** [comment]
@fredrikbaberg You have any idea to fix it?

**Comment by fredrikbaberg** [comment]
How did you try to access the stream? I haven't figured out the proxy part (and not sure I will be able to), so you need to set a port for camera stream.
Anything in the log for the 3dprinter addon with regards to camera?

**Comment by piechade** [comment]
> How did you try to access the stream? I haven't figured out the proxy part (and not sure I will be able to), so you need to set a port for camera stream. Anything in the log for the 3dprinter addon with regards to camera?

Only snapshot is working, the option to set a port missing. I have a working cam and your container. 
This working http://localhost:8080/?action=snapshot.

What i need to do, to get stream working?

**Comment by piechade** [comment]
If I'm able to expose the port of mjpeg, how I can add protection?

**Comment by piechade** [comment]
Any progress on this problem? I want to play with it, but I'm not able to set up a second instance.
Check #280 for more info.

**Comment by fredrikbaberg** [comment]
No progress. I run a reverse proxy as addon (Traefik in my case), and used that for some added protection.
