### ISSUE TITLE
Off-topic: Need help for my fork

### ISSUE THREAD

**Issue by piechade** [fredrikbaberg/hassio-addons#280]
I created a fork of your repo and renamed everything to run two versions of OctoPrint.
One as prod second for mjpeg problem.

https://github.com/piechade/hassio-addons

Everything is building and deploy is working. Like you will see on the link, I removed everything to keep it smaller.
Now the trouble, I can't start it, I get the following error message.

`
s6-overlay-suexec: fatal: can only run as pid 1
`

Is s6 your choice or part of home hassio?

**Comment by fredrikbaberg** [comment]
s6 overlay is included in the base image, it's not something I've added.

**Comment by fredrikbaberg** [comment]
I just noticed this in my feed: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

**Comment by piechade** [comment]
> I just noticed this in my feed: https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Yes, I fixed it already with this. But you image is still better. With your image im able to update octo and my gives only errors. But you idea with treafik is much better. Then I don't need to edit the config.json to expose the port.
