### ISSUE TITLE
Webcam stream not showing in Obico

### ISSUE THREAD

**Issue by tonysprenk** [fredrikbaberg/hassio-addons#284]
I have setup the addon to be reachable outside of ingress and when I access the octopiprint interface through safari everything works as expected but the network stream is not showing in Obico. Any suggestions?

**Comment by fredrikbaberg** [comment]
Sorry, I don't have any experience with Obico so not sure what to do.

**Comment by tonysprenk** [comment]
It seems to work fine with other clients. I guess it’s an issue with Obico. I will ask over there. Thanks for the great addon.
