### ISSUE TITLE
Can't go through setup

### ISSUE THREAD

**Issue by EPDvagyok1** [fredrikbaberg/hassio-addons#296]
I can't go through the add-on login page. It says this: Passive login failed. Please check your [browser's error console](https://faq.octoprint.org/browser-console) and [octoprint.log](https://faq.octoprint.org/logs) for possible reasons.Also make sure that the server is actually running by reloading this page. What can I do with it? Can I create a user to continue the setup without the passive login?
![fdgmbsdfxfdhgfj](https://user-images.githubusercontent.com/119626107/205141949-aac4280d-4cba-4fc9-93c2-fc87567a3254.png)

**Comment by fredrikbaberg** [comment]
Might be related to #290, in that case I don't have a fix right now (other than accessing the addon by SSH to create a new user, and then using external access instead of Ingress).

I haven't had time to work on the addon recently, hopefully I will have some time next week.

**Comment by EPDvagyok1** [comment]
How can I make that through SSH?

**Comment by fredrikbaberg** [comment]
If you haven't been able to solve this, I'd suggest you try with the add-on from: https://github.com/fredrikbaberg/ha-3dprinter-addons.

I don't have a solution for the issue, which I suspect occurred after updating OctoPrint. It's not enough to disable passive login, there is something else that causes the issue.
