### ISSUE TITLE
RASP-CAM PI

### ISSUE THREAD

**Issue by cocolino83** [fredrikbaberg/hassio-addons#316]
Ciao. In anzi tutto, volevo dire che è un grande peccato che questa integrazione non può essere più aggiornata. 
Non riesco in nessun modo a fare funzionare la RASPCAM-IP . Come faccio a farla funzionare? C'è una guida? Grazie mille 
![PXL_20240127_213047301 MP](https://github.com/fredrikbaberg/hassio-addons/assets/88486650/6c31cc8c-f264-4079-80b6-1f2b34d7640f)

**Comment by fredrikbaberg** [comment]
My Italian is very limited so I hope I understood this correctly through translation.

Not sure if it is a question related to one of the add-ons in this repository or just in general. Most of the add-ons related to 3D-printing have been moved to [another repository](https://github.com/fredrikbaberg/ha-3dprinter-addons), as can be seen in the main README.

I have transitioned to use a USB camera, but I believe I was using instructions similar to these before: [Getting the Raspberry Pi Camera to Work on HASSOS](https://gist.github.com/enegaard/a57af286205914bd912270c89650fb1b), it should be enough to follow the steps in the [final comment](https://gist.github.com/enegaard/a57af286205914bd912270c89650fb1b?permalink_comment_id=4786083#gistcomment-4786083). When the camera is available in Home Assistant OS, under Settings/System/Hardware, it should also be available in the camera-mjpg-streamer add-on.
