### ISSUE TITLE
Octprint Develper

### ISSUE THREAD

**Issue by TonMise** [fredrikbaberg/hassio-addons#38]
I recently installed the latest octoprint-dev and I can't get the USB camera to work, can someone help me?

Thanks,
-Ton

**Comment by fredrikbaberg** [comment]
Unfortunately I don't have a camera to test it with. Would it be possible to use the camera integration directly in Home Assistant?

**Comment by fredrikbaberg** [comment]
Right now I won't fix this. If someone has an idea how to enable camera support, feel free to make a suggestion.
