### ISSUE TITLE
cannot install standard version on pi4 (4 gb) with up to date HASS.IO

### ISSUE THREAD

**Issue by alzedd** [fredrikbaberg/hassio-addons#40]
As the title says, if I try to install and activate the standard version i get a message which says my platform is unsupported.

**Comment by olexs** [comment]
Have you tried the "slim" version? Runs perfectly fine on my pi4/4gb.

**Comment by alzedd** [comment]
yes, I tried the dev which I'm running now, but since I want a stable environment, I think it's better to install the stable one.

**Comment by olexs** [comment]
Both "dev" and "standard" Dockerfiles are much older than "slim", "standard" hasn't been touched in two years. I think "standard" is more deprecated than stable at this point.

**Comment by fredrikbaberg** [comment]
I'll have to clean up the versions, have been worried that just updating might break it for some.
Will not have time to do that this weekend, perhaps next.

**Comment by fredrikbaberg** [comment]
> Both "dev" and "standard" Dockerfiles are much older than "slim", "standard" hasn't been touched in two years. I think "standard" is more deprecated than stable at this point.

I have to clean up older versions at some point, have been worried the old version is the only one that works for some. I'll probably just remove "standard".
But it will have to wait at least until next week.

**Comment by alzedd** [comment]
@fredrikbaberg  So, i'll have to use the dev to get an up to date octoprint? No problem, at  least I know it :)

**Comment by fredrikbaberg** [comment]
Sorry for the late reply.
`dev` should be the more stable one, but I'm not sure if it can be updated to the latest version of OctoPrint (1.4.0).
`Experimental` (previously "standard", I renamed it to reduce confusion) is the most recent one, but that one is as it sounds - I haven´t tested it with a printer yet, there may be a lot of issues.

**Comment by blutack** [comment]
Just to let you know, experimental works perfectly with Marlin 2 for me on the latest hass. Only thing I needed to do was change the port from null to 5000 to expose OctoPrint outside of Ingress so I could print directly from Cura.

**Comment by fredrikbaberg** [comment]
> Just to let you know, experimental works perfectly with Marlin 2 for me on the latest hass & Pi 4. Only thing I needed to do was change the port from null to 5000 to expose OctoPrint outside of Ingress so I could print directly from Cura.

Happy to hear that. Note that experimental is currently using Python3 which makes several (most?) plugins unavailable. I decided to let the port be `null` since I have a default user+password set. For the next update I might set a randomized password.

**Comment by LasseSLambertsen** [comment]
> > Just to let you know, experimental works perfectly with Marlin 2 for me on the latest hass & Pi 4. Only thing I needed to do was change the port from null to 5000 to expose OctoPrint outside of Ingress so I could print directly from Cura.
> 
> Happy to hear that. Note that experimental is currently using Python3 which makes several (most?) plugins unavailable. I decided to let the port be `null` since I have a default user+password set. For the next update I might set a randomized password.

How come you use Python3, when it affects plugin usage? :)
Just curious, I'm really loving your work!

**Comment by fredrikbaberg** [comment]
> > > Just to let you know, experimental works perfectly with Marlin 2 for me on the latest hass & Pi 4. Only thing I needed to do was change the port from null to 5000 to expose OctoPrint outside of Ingress so I could print directly from Cura.
> > 
> > 
> > Happy to hear that. Note that experimental is currently using Python3 which makes several (most?) plugins unavailable. I decided to let the port be `null` since I have a default user+password set. For the next update I might set a randomized password.
> 
> How come you use Python3, when it affects plugin usage? :)
> Just curious, I'm really loving your work!

The container became much larger than before, I tried the change to Python3 as a step to reduce the size, but it might not be worth it. I might go back to Python2 when I publish a new version.

Since this is off topic for this issue (my fault) I'll close it.
