### ISSUE TITLE
load webcam

### ISSUE THREAD

**Issue by wafl93** [fredrikbaberg/hassio-addons#41]
how is it possible to import a webcam which is attached via usb into octoprint?
Do i have to configure something in hass.io?

thanks

**Comment by fredrikbaberg** [comment]
Hi,
Unfortunately I don't have a webcam to try it with. I believe the software needed for using a webcam with OctoPrint should be in place (except for "slim"), but I am unable to test it.
As a work-around, is it possible to add the camera directly to Hass.io instead?

**Comment by fredrikbaberg** [comment]
Right now I don't know how to fix this, I'm open to suggestions.
If it is possible to add a camera directy in Home Assistant, that would be easier.

I'll close this issue for now, even if it is not resolved.

**Comment by fredrikbaberg** [comment]
@wafl93 not sure if you have seen it, but from 0.3.0 PiCam should work. I haven't tested with a USB webcam, but I think it might work.

**Comment by kamte** [comment]
I've been trying to get a usb webcam to work, but I've only managed to get snapshots working so far. Has anyone successfully acomplished cam streaming so far?

**Comment by fredrikbaberg** [comment]
> I've been trying to get a usb webcam to work, but I've only managed to get snapshots working so far. Has anyone successfully acomplished cam streaming so far?

I suspect this is through Ingress? If so that is not something I've gotten to work.
