### ISSUE TITLE
No pip in  0.3.0-beta-0

### ISSUE THREAD

**Issue by 2pk** [fredrikbaberg/hassio-addons#79]
I installed the 0.3.0-beta-0 on homeassistant 0.110 and get the following, so not able to install any plugins
 

> The pip command could not be found or does not work correctly for this installation of OctoPrint - please consult the log file for details and if necessary configure it manually. No installation and uninstallation of plugin packages is possible while pip is unavailable.

**Comment by fredrikbaberg** [comment]
Please try restarting the addon or reload the page. I've encountered the issue but haven't figured out why it occurs.

**Comment by fredrikbaberg** [comment]
I'll close this as I haven´t heard anything more. If you get a `pip` error, try to reload the page or possibly restart the addon.
